### ISSUE TITLE
SRL 24.x compatibility: gNMI paths and clab example

### ISSUE THREAD

**Issue by sacckth** [karimra/srl-prometheus-exporter#74]
on `app/server.go` following change needs to happen:
```
--- a/app/server.go
+++ b/app/server.go
@@ -37,7 +37,7 @@ const (
        metricNameRegex      = "[^a-zA-Z0-9_]+"
        serviceName          = "srl-prometheus-exporter"
        retryInterval        = 2 * time.Second
-       gnmiServerUnixSocket = "unix:///opt/srlinux/var/run/sr_gnmi_server"
+       gnmiServerUnixSocket = "unix:///opt/srlinux/var/run/sr_grpc_server_insecure-mgmt"
 )
 ```

Some of the acls need to be changed for this to work on 24 release:
```
updates:

- path: /system/grpc-server[name=insecure-mgmt]
  encoding: json_ietf
  value:
    admin-state: enable
    metadata-authentication: false
    services:
      - gnmi

- path: /acl/acl-filter[name=cpm][type=ipv4]/entry[sequence-id=281]
  encoding: json_ietf
  value:
    action:
      accept: {}
    match:
      ipv4:
        protocol: tcp
      transport:  
        destination-port:
          range:
            start: 8000
            end: 9999

- path: /acl/acl-filter[name=cpm][type=ipv4]/entry[sequence-id=282]
  encoding: json_ietf
  value:
    action:
      accept: {}
    match:
      ipv4:
        protocol: tcp
      transport:  
        source-port:
          range:
            start: 8000
            end: 9999
```
